version: '3.8'
services:
  mongo:
    image: mongo
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    ports:
      - '27018:27017'
    volumes:
      - ./database:/data/db
  frontend:
    build: frontend
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8081
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./frontend:/app   
    depends_on:
      - backend
  backend:
    build: backend
    ports:
      - '8081:8081'
    environment:
      - PORT=8081
      - DB_URI=mongodb://mongo:27017/workoutdiary
      - JWT_SECRET
      - DB_TEST_URI=mongodb://mongo:27017/test
    volumes:
      - /app/node_modules
      - ./backend:/app
    depends_on:
      mongo:
        condition: service_healthy
    command: 
      sh -c "yarn install && yarn build && yarn seeder && yarn start"